// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdpftyozykpmgjaofilj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcGZ0eW96eWtwbWdqYW9maWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NjY3NDQsImV4cCI6MjA5MDE0Mjc0NH0.Ilk2YvQgEekvpGed1gtBoIgLF1MEDNAqmQJeJ3e_pZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});